# SPDX-FileCopyrightText: Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only
---
- name: Prepare Ansible controller
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - ../roles/prepare_ansible_controller

- name: Validate LDAP Multi-Master installation prerequisites
  hosts: all
  order: inventory
  gather_facts: yes
  roles:
     - ../roles/pre_installation_checks

- name: Install and configure LDAP Multi-Master
  hosts: masterDirectoryServers
  order: inventory
  gather_facts: yes
  roles:
     - ../roles/install_multimaster