# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only
---
- name: Install mailbox db connector Ubuntu  
  become: true
  apt: name={{ item }} state=present
  with_items:
    - "{{ mailbox_dbconnectors_packages }}"
  when: 
    - ansible_os_family == "Debian"
    - inventory_hostname in groups['dbsConnectorServers']
  tags:
    - install-carbonio-dbconnectors

- name: Install files db connector Ubuntu  
  become: true
  apt: name={{ item }} state=present
  with_items:
    - "{{ files_dbconnectors_packages }}"
  when: 
    - ansible_os_family == "Debian"
    - inventory_hostname in groups['dbsConnectorServers']
    - groups['filesServers'] | length > 0
  tags:
    - install-carbonio-dbconnectors

- name: Install docs db connector Ubuntu  
  become: true
  apt: name={{ item }} state=present
  with_items:
    - "{{ docs_dbconnectors_packages }}"
  when: 
    - ansible_os_family == "Debian"
    - inventory_hostname in groups['dbsConnectorServers']
    - groups['docsServers'] | length > 0 
  tags:
    - install-carbonio-dbconnectors

- name: Install tasks db connector Ubuntu  
  become: true
  apt: name={{ item }} state=present
  with_items:
    - "{{ task_dbconnectors_packages }}"
  when: 
    - ansible_os_family == "Debian"
    - inventory_hostname in groups['dbsConnectorServers']
    - groups['taskServers'] | length > 0
  tags:
    - install-carbonio-dbconnectors

- name: Install ws_collaboration db connector Ubuntu  
  become: true
  apt: name={{ item }} state=present
  with_items:
    - "{{ ws_collaboration_dbconnectors_packages }}"
  when: 
    - ansible_os_family == "Debian"
    - inventory_hostname in groups['dbsConnectorServers']
    - groups['workStreamServers'] | length > 0
  tags:
    - install-carbonio-dbconnectors

- name: Install message_dispatcher db connector Ubuntu  
  become: true
  apt: name={{ item }} state=present
  with_items:
    - "{{ message_dispatcher_dbconnectors_packages }}"
  when:
    - ansible_os_family == "Debian"
    - inventory_hostname in groups['dbsConnectorServers']
    - groups['workStreamServers'] | length > 0
  tags:
    - install-carbonio-dbconnectors

- name: Install notification_push db connector Ubuntu  
  become: true
  apt: name={{ item }} state=present
  with_items:
    - "{{ notification_push_dbconnectors_packages }}"
  when:
    - ansible_os_family == "Debian"
    - inventory_hostname in groups['dbsConnectorServers']
    - groups['workStreamServers'] | length > 0
  tags:
    - install-carbonio-dbconnectors

##### RHEL
- name: Install mailbox db connector RHEL  
  become: true
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ mailbox_dbconnectors_packages }}"
  when: 
    - ansible_os_family == "RedHat"
    - inventory_hostname in groups['dbsConnectorServers']
  tags:
    - install-carbonio-dbconnectors

- name: Install files db connector RHEL  
  become: true
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ files_dbconnectors_packages }}"
  when: 
    - ansible_os_family == "RedHat"
    - inventory_hostname in groups['dbsConnectorServers']
    - groups['filesServers'] | length > 0
  tags:
    - install-carbonio-dbconnectors

- name: Install docs db connector RHEL  
  become: true
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ docs_dbconnectors_packages }}"
  when: 
    - ansible_os_family == "RedHat"
    - inventory_hostname in groups['dbsConnectorServers']
    - groups['docsServers'] | length > 0
  tags:
    - install-carbonio-dbconnectors

- name: Install tasks db connector RHEL  
  become: true
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ task_dbconnectors_packages }}"
  when: 
    - ansible_os_family == "RedHat"
    - inventory_hostname in groups['dbsConnectorServers']
    - groups['taskServers'] | length > 0
  tags:
    - install-carbonio-dbconnectors

- name: Install wscollaboration db connector RHEL  
  become: true
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ ws_collaboration_dbconnectors_packages }}"
  when: 
    - ansible_os_family == "RedHat"
    - inventory_hostname in groups['dbsConnectorServers']
    - groups['workStreamServers'] | length > 0
  tags:
    - install-carbonio-dbconnectors

- name: Install message dispatcher db connector RHEL  
  become: true
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ message_dispatcher_dbconnectors_packages }}"
  when:
    - ansible_os_family == "RedHat"
    - inventory_hostname in groups['dbsConnectorServers']
    - groups['workStreamServers'] | length > 0
  tags:
    - install-carbonio-dbconnectors

- name: Install notification push db connector RHEL  
  become: true
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ notification_push_dbconnectors_packages }}"
  when:
    - ansible_os_family == "RedHat"
    - inventory_hostname in groups['dbsConnectorServers']
    - groups['workStreamServers'] | length > 0
  tags:
    - install-carbonio-dbconnectors
