# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only
---
- name: Load OS-specific variables
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - ../vars/{{ ansible_os_family }}.yml
    - ../vars/{{ ansible_distribution_release }}.yml
  tags:
    - always

- name: Create kafka group
  ansible.builtin.group:
    name: '{{ kafka_group }}'
    state: present
    system: yes
  when: kafka_create_user_group | bool
  tags:
    - kafka_group

- name: Create kafka user
  ansible.builtin.user:
    name: '{{ kafka_user }}'
    group: '{{ kafka_group }}'
    state: present
    createhome: yes
    home: '/var/lib/queue/'
    system: yes
  when: kafka_create_user_group | bool
  tags:
    - kafka_user

- name: Create directory for kafka data log files
  ansible.builtin.file:
    path: /var/lib/queue/kafka/logs
    state: directory
    recurse: yes
    owner: '{{ kafka_user }}'
    group: '{{ kafka_group }}'
    mode: 0755

- name: Create directory for kafka config
  ansible.builtin.file:
    path: /opt/kafka/config
    state: directory
    recurse: yes
    owner: '{{ kafka_user }}'
    group: '{{ kafka_group }}'
    mode: 0755

- name: Install jre [Ubuntu]
  ansible.builtin.apt:
    name: openjdk-17-jre-headless
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install jre [RHEL]
  ansible.builtin.yum:
    name: java-17-openjdk-headless
    state: present
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Check if Kafka has already been downloaded and unpacked
  ansible.builtin.stat:
    path: '{{ kafka_dir }}_{{ kafka_scala_version }}-{{ kafka_version }}'
  register: dir

- name: Download Apache Kafka
  ansible.builtin.get_url:
    url: '{{ kafka_download_base_url }}/{{ kafka_version }}/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz'
    dest: /tmp
    validate_certs: false
    mode: 0644
  when: offline is undefined
  tags:
    - kafka_download

- name: Upload Apache Kafka
  ansible.builtin.copy:
      src: kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz
      dest: /tmp/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz
      mode: '0644'
  when: offline is defined
  tags:
    - kafka_download

- name: Unpack Apache Kafka
  ansible.builtin.unarchive:
    src: /tmp/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz
    dest: '{{ kafka_dir }}'
    copy: no
    group: '{{ kafka_group }}'
    owner: '{{ kafka_user }}'
    extra_opts: ['--strip-components=1', '--show-stored-names']
  # when: not dir.stat.exists
  tags:
    - kafka_unpack

- name: Create directory for symlink to kafka configuration files
  ansible.builtin.file:
    path: /etc/kafka
    state: directory
    group: '{{ kafka_group }}'
    owner: '{{ kafka_user }}'
    mode: 0755
  tags:
    - kafka_dirs

- name: Template configuration file to server.properties
  ansible.builtin.template:
    src: server.properties.j2
    dest: '{{ kafka_dir }}/config/server.properties'
    group: '{{ kafka_group }}'
    owner: '{{ kafka_user }}'
    mode: 0644
  tags:
    - kafka_config

- name: Template configuration file to producer.properties
  ansible.builtin.template:
    src: producer.properties.j2
    dest: '{{ kafka_dir }}/config/producer.propertiess'
    group: '{{ kafka_group }}'
    owner: '{{ kafka_user }}'
    mode: 0644
  tags:
    - kafka_config

- name: Template kafka systemd service
  ansible.builtin.template:
    src: carbonio-kafka.service.j2
    dest: '{{ kafka_unit_path }}'
    group: '{{ kafka_group }}'
    owner: '{{ kafka_user }}'
    mode: 0644
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version > '6' or ansible_os_family == "Debian"
  tags:
    - kafka_service

- name: Install and start the kafka service
  ansible.builtin.service:
    name: carbonio-kafka
    state: started
    enabled: yes
  # when: kafka_start
  tags:
    - kafka_service

- name: Delete the kafka archive file
  ansible.builtin.file:
    path: /tmp/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz
    state: absent
  tags:
    - kafka_cleanup
