# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only
---
- name: Add  Kafka brooker to the mailboxes
  become: true
  become_method: su
  become_user: zextras
  command: "/opt/zextras/bin/carbonio config set global brokers \"{{ groups[\"kafka\"][0]}}:9092,{{ groups[\"kafka\"][1]}}:9092,{{ groups[\"kafka\"][2]}}:9092\""
  when: inventory_hostname in groups["applicationServers"]
  tags:
    - kafka-mailbox

- name: Check Kafka config status
  become: true
  become_method: su
  become_user: zextras
  command: "/opt/zextras/bin/carbonio config get global brokers"
  when: inventory_hostname in groups["applicationServers"]
  register: kafka_status
  tags:
    - kafka-mailbox


- name: Print Kafka config status
  debug:
    msg: "{{ kafka_status.stdout_lines }}"