---
# tasks file for promote_multimaster
- name: Check if read replica configured
  ansible.builtin.package_facts:
      manager: auto

# - name: Enable MMR on existing LDAP master
#   become: true
#   become_method: su
#   become_user: zextras
#   command: "/opt/zextras/libexec/zmldapenable-mmr -s 1 -m ldap://{{ groups[\"NewMutliMasterDirectoryServers\"][0]}}:389/"
#   when: inventory_hostname in groups["masterDirectoryServers"]

- name: Change local conf on first master
  become: true
  become_method: su
  become_user: zextras
  command: "zmlocalconfig -e ldap_master_url=\"ldap://{{ groups[\"masterDirectoryServers\"][0]}}:389 ldap://{{ groups[\"NewMutliMasterDirectoryServers\"][0]}}:389\""
  when: inventory_hostname in groups["masterDirectoryServers"]

- name: Restart carbonio on first LDAP master
  become: true
  become_method: su
  become_user: zextras
  command: "/opt/zextras/bin/zmcontrol restart"
  when: inventory_hostname in groups["masterDirectoryServers"]

- name: Stop zimbra services on second LDAP master
  become: true
  become_method: su
  become_user: zextras
  command: "/opt/zextras/bin/zmcontrol stop"
  when: "'carbonio-directory-server' in ansible_facts.packages and inventory_hostname in groups[\"NewMutliMasterDirectoryServers\"]"

# - name: Promote second LDAP master to multimaster
#   become: true
#   become_method: su
#   become_user: zextras
#   command: "/opt/zextras/libexec/zmldappromote-replica-mmr -s 2"
#   when: "'carbonio-directory-server' in ansible_facts.packages and inventory_hostname in groups[\"NewMutliMasterDirectoryServers\"]"

- name: Change local conf on second master
  become: true
  become_method: su
  become_user: zextras
  command: "zmlocalconfig -e ldap_master_url=\"ldap://{{ groups[\"NewMutliMasterDirectoryServers\"][0]}}:389 ldap://{{ groups[\"masterDirectoryServers\"][0]}}:389\""
  when: "'carbonio-directory-server' in ansible_facts.packages and inventory_hostname in groups[\"NewMutliMasterDirectoryServers\"]"

- name: Restart carbonio on second LDAP master
  become: true
  become_method: su
  become_user: zextras
  command: "/opt/zextras/bin/zmcontrol restart"
  when: "'carbonio-directory-server' in ansible_facts.packages and inventory_hostname in groups[\"NewMutliMasterDirectoryServers\"]"