- name: Update repos [Ubuntu]
  become: true
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian" and inventory_hostname not in groups["masterDirectoryServers"] and inventory_hostname not in groups["replicaDirectoryServers"]
  tags:
      - haproxy

- name: Install haproxy packages [Ubuntu]
  become: true
  apt: name={{ item }} state=present
  with_items:
    - "{{ haproxy_packages }}"
  when: ansible_os_family == "Debian" and inventory_hostname not in groups["masterDirectoryServers"] and inventory_hostname not in groups["replicaDirectoryServers"]
  tags:
    - haproxy

- name: Install haproxy packages [RHEL]
  become: true
  yum: name={{ item }} state=present
  with_items:
    - "{{ haproxy_packages }}"
  when: ansible_os_family == "RedHat" and inventory_hostname not in groups["masterDirectoryServers"] and inventory_hostname not in groups["replicaDirectoryServers"]
  tags:
    - haproxy

- name: Template configuration file for haproxy
  become: true
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  when: inventory_hostname not in groups["dbsConnectorServers"] and inventory_hostname not in groups["masterDirectoryServers"] and inventory_hostname not in groups["replicaDirectoryServers"]
  tags:
    - haproxy

- name: Start the haproxy service
  ansible.builtin.service:
    name: haproxy
    state: restarted
    enabled: yes
  when: inventory_hostname not in groups["masterDirectoryServers"] and inventory_hostname not in groups["replicaDirectoryServers"]
  tags:
    - haproxy

- name: Use haproxy for LDAP connection
  become: true
  become_method: su
  become_user: zextras
  command: "/opt/zextras/bin/zmlocalconfig -e {{ item }}"
  loop:
    - "ldap_url='ldap://localhost:389'"
    - "ldap_master_url='ldap://localhost:389'"
  when: inventory_hostname not in groups["masterDirectoryServers"] and inventory_hostname not in groups["replicaDirectoryServers"]
  tags:
    - haproxy

- name: Restart carbonio
  become: true
  become_method: su
  become_user: zextras
  command: "/opt/zextras/bin/zmcontrol restart"
  when: inventory_hostname in groups["applicationServers"]
  tags:
    - haproxy
