# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only
---
- hosts: postgresServers
  order: inventory
  gather_facts: yes
  roles:
     - ../roles/install_patroni

- name: HAProxy installation for infrastructures with Multi Master LDAP
  hosts: all
  gather_facts: yes
  tasks:
    - name: HAProxy installation for infrastructures with Multi Master LDAP
      import_role:
        name: ../roles/install_haproxy
      when: groups['masterDirectoryServers'] | length > 1
      tags:
        - haproxy

- name: HAProxy Installation for infrastructures without Multi Master LDAP
  hosts: dbsConnectorServers
  gather_facts: yes
  tasks:
    - name: HAProxy installation for infrastructures without Multi Master LDAP
      import_role:
        name: ../roles/install_haproxy
      when: groups['masterDirectoryServers'] | length == 1
      tags:
        - haproxy

- name: Move DB connectors 
  hosts: all
  gather_facts: yes
  tasks:
    - name: Move DB connectors for full HA
      import_role:
        name: ../roles/move_dbconnectors
      tags:
        - move-dbconnectors