# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only
---
- hosts: postgresServers
  order: inventory
  gather_facts: yes
  roles:
     - ../roles/install_replica_postgres