# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only
---
- hosts: postgresServers
  order: inventory
  gather_facts: yes
  roles:
     - ../roles/install_patroni

- name: Check the type of the installation
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check the type of the installation
      pause:
        prompt: "Is this a full HA installation? (yes/no)"
      register: full_ha
      tags:
        - haproxy

    - name: Faif if user wrote a wrong value
      fail:
        msg: "Invalid input. Please enter 'yes' or 'no'."
      when: full_ha.user_input not in ['yes', 'no']
      tags:
        - haproxy

    - name: Set global vars for full_ha
      add_host:
        name: "{{ item }}"
        full_ha: "{{ full_ha.user_input }}"
      with_items: "{{ groups['all'] }}"
      tags:
        - haproxy

- name: HAProxy installation for full HA
  hosts: all
  gather_facts: yes
  tasks:
    - name: HAProxy installation for full HA
      import_role:
        name: ../roles/install_haproxy
      when: full_ha == "yes"
      tags:
        - haproxy

- name: HAProxy Installation for non-full HA
  hosts: dbsConnectorServers
  gather_facts: yes
  tasks:
    - name: HAProxy installation for non-full HA
      import_role:
        name: ../roles/install_haproxy
      when: full_ha == "no"
      tags:
        - haproxy

- name: Move DB connectors 
  hosts: all
  gather_facts: yes
  tasks:
    - name: Move DB connectors for full HA
      import_role:
        name: ../roles/move_dbconnectors
      tags:
        - move-dbconnectors