---
- hosts: postgresServers
  order: inventory
  gather_facts: yes
  roles:
     - ../roles/install_patroni

- hosts: dbsConnectorServers,applicationServers
  order: inventory
  gather_facts: yes
  roles:
     - ../roles/configure_patroni_carbonio