# SPDX-FileCopyrightText: Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only
---
- name: Update repos [Ubuntu]
  become: true
  ansible.builtin.apt:
    update_cache: true
  when: 
    - ansible_facts.os_family == "Debian"
    - inventory_hostname not in groups['masterDirectoryServers']
    - inventory_hostname not in groups['replicaDirectoryServers']
  tags:
      - haproxy

- name: Install haproxy packages [Ubuntu]
  become: true
  ansible.builtin.apt: name={{ item }} state=present
  with_items:
    - "{{ haproxy_packages }}"
  when: 
    - ansible_facts.os_family == "Debian"
    - inventory_hostname not in groups['masterDirectoryServers']
    - inventory_hostname not in groups['replicaDirectoryServers']
  tags:
    - haproxy

- name: Install haproxy packages [RHEL]
  become: true
  ansible.builtin.yum: name={{ item }} state=present
  with_items:
    - "{{ haproxy_packages }}"
  when: 
    - ansible_facts.os_family == "RedHat"
    - inventory_hostname not in groups['masterDirectoryServers']
    - inventory_hostname not in groups['replicaDirectoryServers']
  tags:
    - haproxy

- name: Template configuration file for haproxy
  become: true
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  when: 
    - inventory_hostname not in groups['masterDirectoryServers']
    - inventory_hostname not in groups['replicaDirectoryServers']
  tags:
    - haproxy

- name: Start the haproxy service
  ansible.builtin.service:
    name: haproxy
    state: restarted
    enabled: true
  when: 
    - inventory_hostname not in groups['masterDirectoryServers']
    - inventory_hostname not in groups['replicaDirectoryServers']
  tags:
    - haproxy

- name: Use haproxy for LDAP connection
  become: true
  become_method: su
  become_user: zextras
  ansible.builtin.command: "/opt/zextras/bin/zmlocalconfig -e {{ item }}"
  loop:
    - "ldap_url='ldap://localhost:389'"
    - "ldap_master_url='ldap://localhost:389'"
  when: 
    - inventory_hostname not in groups['masterDirectoryServers']
    - inventory_hostname not in groups['replicaDirectoryServers']
    - groups['masterDirectoryServers'] | length > 1
  tags:
    - haproxy

- name: Restart carbonio
  become: true
  become_method: su
  become_user: zextras
  ansible.builtin.command: "/opt/zextras/bin/zmcontrol restart"
  when: 
    - inventory_hostname in groups['applicationServers']
    - ansible_facts.distribution_major_version != "9"
    - ansible_facts.distribution_major_version != "24"
  tags:
    - haproxy

- name: Restart carbonio  [Sysd]
  become: true
  ansible.builtin.systemd_service:
    name: carbonio.target
    state: restarted
  when: 
    - inventory_hostname in groups['applicationServers']
    - ansible_facts.distribution_major_version == "9" or ansible_facts.distribution_major_version == "24"
  tags:
    - haproxy