# SPDX-FileCopyrightText: Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only
---
- name: Install Carbonio license service [Ubuntu]
  become: true
  ansible.builtin.apt:
    name: carbonio-license-service
    state: present
  when:
    - ansible_facts.os_family == "Debian"
    - inventory_hostname in groups["masterDirectoryServers"]
    - ldap_role == "mmr"

- name: Install Carbonio license service [RHEL]
  become: true
  ansible.builtin.yum:
    name: carbonio-license-service
    state: present
  when:
    - ansible_facts.os_family == "RedHat"
    - inventory_hostname in groups["masterDirectoryServers"]
    - ldap_role == "mmr"

- name: Copy pending setups script
  become: true
  ansible.builtin.template:
    src: apply-pending-setups.sh.j2
    dest: /tmp/apply-pending-setups.sh
    mode: "0755"
  when:
    - inventory_hostname in groups["masterDirectoryServers"]
    - ldap_role == "mmr"
  tags:
    - execute-pending-setups

- name: Run pending setups for license service
  become: true
  ansible.builtin.command: /tmp/apply-pending-setups.sh {{ carbonio_mesh_password }}
  when:
    - inventory_hostname in groups["masterDirectoryServers"]
    - ldap_role == "mmr"
  tags:
    - execute-pending-setups

- name: Remove pending setups script
  become: true
  ansible.builtin.file:
    path: /tmp/apply-pending-setups.sh
    state: absent
  when:
    - inventory_hostname in groups["masterDirectoryServers"]
    - ldap_role == "mmr"
  tags:
    - execute-pending-setups