---
# tasks file for install_multimaster
- name: Check if read replica configured
  ansible.builtin.package_facts:
      manager: auto

- name: Enable MMR on existing LDAP master
  become: true
  become_method: su
  become_user: zextras
  command: "/opt/zextras/libexec/zmldapenable-mmr -s 1 -m ldap://{{ groups[\"NewMutliMasterDirectoryServers\"][0]}}:389/"
  when: inventory_hostname in groups["masterDirectoryServers"]

- name: Change local conf on first master
  become: true
  become_method: su
  become_user: zextras
  command: "zmlocalconfig -e ldap_master_url=\"ldap://{{ groups[\"masterDirectoryServers\"][0]}}:389 ldap://{{ groups[\"NewMutliMasterDirectoryServers\"][0]}}:389\""
  when: inventory_hostname in groups["masterDirectoryServers"]

- name: Restart carbonio on first LDAP master
  become: true
  become_method: su
  become_user: zextras
  command: "/opt/zextras/bin/zmcontrol restart"
  when: inventory_hostname in groups["masterDirectoryServers"]

- name: Stop zimbra services on second LDAP master
  become: true
  become_method: su
  become_user: zextras
  command: "/opt/zextras/bin/zmcontrol stop"
  when: "'carbonio-directory-server' not in ansible_facts.packages and inventory_hostname in groups[\"NewMutliMasterDirectoryServers\"]"

- name: Install carbonio-directory-server [Ubuntu]
  become: true
  apt: name={{ item }} state=present
  with_items:
      - carbonio-directory-server
  when: "ansible_os_family == \"Debian\" and 'carbonio-directory-server' not in ansible_facts.packages and inventory_hostname in groups[\"NewMutliMasterDirectoryServers\"]"

- name: Install carbonio-directory-server [RHEL]
  become: true
  yum: name={{ item }} state=present
  with_items:
      - carbonio-directory-server
  when: "ansible_os_family == \"RedHat\" and 'carbonio-directory-server' not in ansible_facts.packages and inventory_hostname in groups[\"NewMutliMasterDirectoryServers\"]"

- name: Remove old configuration
  become: true
  ansible.builtin.shell: "rm /opt/zextras/config.* && rm /opt/zextras/.install_history"
  when: "'carbonio-directory-server' not in ansible_facts.packages and inventory_hostname in groups[\"NewMutliMasterDirectoryServers\"]"

- name: Manage Consul password
  ansible.builtin.set_fact:
      carbonio_mesh_password: "{{ lookup('ansible.builtin.password', inventory_file + '_consulpassword', chars=['ascii_letters', 'digits'], length=8) }}"
  tags:
    - execute-pending-setups
    
    
- name: Copy scripts to remote host
  become: true
  ansible.builtin.copy:
    src: apply-pending-setups.sh
    dest: /tmp/apply-pending-setups.sh
    mode: '0755'
  when: "'carbonio-directory-server' not in ansible_facts.packages and inventory_hostname in groups[\"NewMutliMasterDirectoryServers\"]"
  tags:
    - execute-pending-setups
    
- name: Run Carbonio pending-setups
  become: true
  command: /tmp/apply-pending-setups.sh {{ carbonio_mesh_password }}
  register: pso
  when: "'carbonio-directory-server' not in ansible_facts.packages and inventory_hostname in groups[\"NewMutliMasterDirectoryServers\"]"
  tags:
    - execute-pending-setups
    
- name: Remove scripts from remote host
  become: true
  ansible.builtin.file:
    state: absent
    path: /tmp/apply-pending-setups.sh
  when: "'carbonio-directory-server' not in ansible_facts.packages and inventory_hostname in groups[\"NewMutliMasterDirectoryServers\"]"
  tags:
    - execute-pending-setups

- name: Manage ldap password
  ansible.builtin.set_fact:
      carbonio_ldap_password: "{{ lookup('ansible.builtin.password', inventory_file + '_ldap_password', chars=['ascii_letters', 'digits'], length=8) }}"
  tags:
    - execute-carbonio-bootstrap

- name: Create config file
  template:
    src: carbonio-config.txt.j2
    dest: /tmp/carbonio-config.txt
  when: "'carbonio-directory-server' not in ansible_facts.packages and inventory_hostname in groups[\"NewMutliMasterDirectoryServers\"]"
  tags:
    - execute-carbonio-bootstrap
    
- name: run Carbonio Bootstrap
  become: true
  command: /usr/bin/carbonio-bootstrap -c /tmp/carbonio-config.txt
  when: "'carbonio-directory-server' not in ansible_facts.packages and inventory_hostname in groups[\"NewMutliMasterDirectoryServers\"]"
  tags:
    - execute-carbonio-bootstrap

- name: Change local conf on second master
  become: true
  become_method: su
  become_user: zextras
  command: "zmlocalconfig -e ldap_master_url=\"ldap://{{ groups[\"NewMutliMasterDirectoryServers\"][0]}}:389 ldap://{{ groups[\"masterDirectoryServers\"][0]}}:389\""
  when: "'carbonio-directory-server' not in ansible_facts.packages and inventory_hostname in groups[\"NewMutliMasterDirectoryServers\"]"

- name: Restart carbonio on second LDAP master
  become: true
  become_method: su
  become_user: zextras
  command: "/opt/zextras/bin/zmcontrol restart"
  when: "'carbonio-directory-server' not in ansible_facts.packages and inventory_hostname in groups[\"NewMutliMasterDirectoryServers\"]"
