- hosts: kafka
  order: inventory
  gather_facts: yes
  roles:
     - ../roles/install_kafka

- hosts: applicationServers
  order: inventory
  gather_facts: yes
  roles:
     - ../roles/configure_kafka_mailbox