# SPDX-FileCopyrightText: Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only
---
- name: Prepare Ansible controller
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - ../roles/prepare_ansible_controller
    
- name: Validate Kafka installation prerequisites
  hosts: all
  order: inventory
  gather_facts: yes
  roles:
     - ../roles/pre_installation_checks

- name: Install and configure Kafka
  hosts: kafka
  order: inventory
  gather_facts: yes
  vars:
      offline: true
  roles:
     - ../roles/install_kafka

- name: Configure Kafka brokers on Application Servers
  hosts: applicationServers
  order: inventory
  gather_facts: yes
  roles:
     - ../roles/configure_kafka_mailbox