# SPDX-FileCopyrightText: Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
# tasks file for pre_installation_checks
  - ansible.builtin.import_tasks: validate_inventory_chats.yml
  - ansible.builtin.import_tasks: validate_password_files.yml
  - ansible.builtin.import_tasks: validate_inventory_values.yml
