# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
# tasks file for pre_installation_checks
  - import_tasks: validate_inventory_chats.yml
  - import_tasks: validate_password_files.yml
  - import_tasks: validate_inventory_values.yml
